//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PIA PA.rc
//
#define IDD_LOGIN                       101
#define IDD_REGISTER                    103
#define IDD_INFOVENDEDOR                105
#define IDD_ENVIOS                      107
#define IDD_ALTAENVIO                   109
#define IDD_ALTA                        109
#define IDD_PRODUCTOS                   111
#define IDD_RESUMENENVIO                113
#define IDD_MODIFY                      115
#define IDR_MENU1                       118
#define IDD_MODAL                       119
#define IDD_PRODUCTLIST                 121
#define IDD_MODIFYPROD                  123
#define IDD_DIALOG1                     127
#define TXT_NAME                        1001
#define LBL_NAME                        1002
#define LBL_PASSWORD                    1003
#define TXT_PASSWORD                    1004
#define LBL_WELCOME                     1005
#define LBL_REGISTERFREE                1006
#define BTN_REGISTER                    1007
#define BTN_ENTER                       1008
#define TXT_RNAME                       1009
#define TXT_RPASSWORD                   1010
#define LBL_NOMBRE                      1011
#define LBL_CONTRASENA                  1012
#define BTN_REGISTER2                   1013
#define TXT_COMPLETENAME                1014
#define BTN_RETURN                      1014
#define TXT_ALIAS                       1015
#define LBL_NOMBRE2                     1015
#define LBL_COMPLETENAME                1016
#define TXT_RNAMEP                      1016
#define LBL_ALIAS                       1017
#define LBL_NOMBRE3                     1017
#define LBL_FOTO                        1018
#define TXT_APELLIDOS                   1018
#define IDC_BUTTON1                     1019
#define BTN_CARGARP1                    1019
#define BTN_EXITLOGIN                   1019
#define BTN_MODIFICAPRODUCTO            1019
#define LBL_NOMBRE4                     1019
#define BTN_CALCULARPRECIO              1019
#define PB_FOTO                         1020
#define IDC_BUTTON2                     1020
#define BTN_MODIFYENV                   1020
#define BTN_BORRARPRODUCTO              1020
#define LBL_NOMBRE5                     1020
#define IDC_LIST1                       1021
#define TXT_CORREO                      1021
#define IDC_BUTTON3                     1022
#define IDC_COMBO1                      1022
#define BTN_MOSTRARENVIO                1022
#define BTN_CHECA                       1022
#define LBL_CONFIRMARCONTRASENA         1022
#define IDC_BUTTON4                     1023
#define IDC_EDIT1                       1023
#define PB_SHOWFOTOP1                   1023
#define TXT_CONFIRMPASSWORD             1023
#define BTN_DELETEENV                   1023
#define IDC_BUTTON5                     1024
#define IDC_EDIT2                       1024
#define IDC_EDIT3                       1025
#define PB_SHOWFOTOP2                   1025
#define IDC_EDIT4                       1026
#define IDC_EDIT5                       1027
#define IDC_EDIT6                       1028
#define IDC_EDIT7                       1029
#define IDC_COMBO2                      1030
#define IDC_COMBO3                      1031
#define IDC_COMBO4                      1032
#define IDC_BUTTON6                     1033
#define CB_PRODUCTS                     1034
#define LBL_PRODUCT                     1035
#define LBL_CANTIDAD                    1036
#define TXT_CANTIDAD                    1037
#define LBL_MONTO                       1038
#define TXT_MONTO                       1039
#define LBL_ST                          1040
#define TXT_ST                          1041
#define LBL_EXIT                        1042
#define BTN_EXIT                        1043
#define BTN_CANCEL                      1044
#define BTN_CONFIRMIV                   1044
#define BTN_IMGIV                       1045
#define LBL_NDP                         1046
#define LBL_CEEI                        1047
#define LBL_CDP                         1048
#define LBL_MARCA                       1049
#define LBL_DESCRIPCION                 1050
#define TXT_NDP                         1051
#define TXT_CEEI                        1052
#define TXT_CDP                         1053
#define TXT_MARCA                       1054
#define TXT_DESCRIPCION                 1055
#define BTN_CARGARP2                    1056
#define PB_FOTOP1                       1057
#define PB_FOTOP2                       1058
#define LBL_FOTOP                       1059
#define BTN_CONFIRMARPRODUCTO           1060
#define BTN_NUEVOENVIO                  1061
#define LBL_PRECIO                      1061
#define TXT_PRECIO                      1062
#define BTN_MOSTRARPRODUCTOS            1063
#define TXT_NDPM                        1064
#define TXT_CEEIM                       1065
#define TXT_CDPM                        1066
#define TXT_MARCAM                      1067
#define TXT_DESCRIPCIONM                1068
#define TXT_PRECIOM                     1069
#define BTN_CARGARP1M                   1070
#define BTN_CARGARP2M                   1071
#define PB_FOTOP1M                      1072
#define PB_FOTOP2M                      1073
#define BTN_CONFIRMARCAMBIO             1074
#define LBL_NDPM                        1075
#define LBL_CEEIM                       1076
#define LBL_CDPM                        1077
#define LBL_MARCAM                      1078
#define LBL_DESCRIPCIONM                1079
#define LBL_PRECIOM                     1080
#define LBL_FOTOPM                      1081
#define TXT_COLONIA                     1083
#define TXT_CIUDAD                      1084
#define TXT_ESTADO                      1085
#define TXT_MENSAJE                     1086
#define DTP_FECHA                       1088
#define LBL_CANT                        1090
#define LBL_COD                         1091
#define LBL_PREC                        1092
#define LBL_MARC                        1093
#define LBL_DESC                        1094
#define IDC_DTPR                        1097
#define CB_PRODUCTSN                    1098
#define TXT_CANTIDADN                   1099
#define TXT_STN                         1101
#define TXT_COLONIAN                    1102
#define TXT_CIUDADN                     1103
#define TXT_ESTADON                     1104
#define TXT_MENSAJEN                    1105
#define DTP_FECHAN                      1106
#define BTN_CHECAN                      1107
#define BTN_CANCELN                     1108
#define LBL_PAGAR                       1109
#define BTN_gr                          1110
#define LBL_JK                          1111
#define LBL_PROD                        1112
#define LBL_PROD2                       1113
#define LBL_PROD3                       1114
#define IDC_LIST11                      1115
#define LBL_PROD1                       1116
#define LBL_CANT1                       1117
#define LBL_PREC1                       1118
#define LBL_ST1                         1119
#define LBL_COL1                        1120
#define LBL_CIUDAD1                     1121
#define LBL_EDO1                        1122
#define LBL_MSJ1                        1123
#define LB_ENVIOSDELETE                 1124
#define ID_WATCHINFO                    40014
#define ID_PRODUCTOS_VER                40020
#define ID_SALIR                        40021
#define ID_ENVIOS                       40024
#define BTN_RESUMENENVIO                40025
#define ID_SALIRDELAAPLICACION          40026
#define ID_SALIR_SALIRDELAAPLICACI40027 40027
#define ID_PRODUCTOS_ELIMINARPRODUCTO   40028
#define ID_PRODUCTOS_EDITARPRODUCTO     40029
#define ID_PRODUCTOS_MISPRODUCTOS       40030
#define ID_ENV40031                     40031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         40032
#define _APS_NEXT_CONTROL_VALUE         1125
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
